### ISSUE TITLE
Remove Lodash dependency

### ISSUE THREAD

**Issue by daffl** [feathersjs/feathers-errors#10]
Currently when installing Feathers you get a warning because of an old Lodash dependency used in feathers-errors. Since it is only used in one place we can probably just remove it.

**Comment by ekryski** [comment]
I can tackle this, this week. I'll probably just convert this guy over to ES6 as well.

**Comment by daffl** [comment]
Maybe we can put the error types into a separate repo at `feathers-error-types`. Something I've been wondering is if it is really possible to make a generic error handler or if you'll eventually have to modify it for your app anyway. In the generated app I currently just add one as its own middleware (https://github.com/feathersjs/generator-feathers/blob/app-architecture/app/templates/static/src/middleware/error.js) that just spits out an HTML page or the JSON error that you can then modify as needed.

**Comment by ekryski** [comment]
Ya I've been considering that as well. I'd rather see error types go with core as a dependency and then move this to part of the boilerplate as middleware. That way it's easy for people to customize or get rid of if they want.

**Comment by ekryski** [comment]
Closing in favour of this: https://github.com/feathersjs/feathers-errors/issues/11
