### ISSUE TITLE
Full Validation Error Object not passed to client promise

### ISSUE THREAD

**Issue by eikaramba** [feathersjs/feathers-errors#61]
### Steps to reproduce

I have the problem that a validation **error in feathers-sequelize is not completely(not the whole object) passed to the catch block of my client's service promise**. More precisely, after looking into it, either the problem is that the error is "converted" here(https://github.com/feathersjs/feathers-rest/blob/master/src/client/base.js#L60) at all OR the actual error lib is doing something wrong here(https://github.com/feathersjs/feathers-errors/blob/master/src/index.js#L216);

In the latter case i fixed it by forcing it to extend to an object. So the Code in Line 216 in the error lib(2nd link) is now actually:
```
if (typeof error === 'object') {
    return Object.assign({},result, error);
}
```

### Expected behavior
Seeing the full error object, with the error array, statusCode etc.

![grafik](https://cloud.githubusercontent.com/assets/1320525/22861987/d47cc580-f125-11e6-84c2-dc371d5e775f.png)

### Actual behavior
I'm only getting the concatinated error message:
![grafik](https://cloud.githubusercontent.com/assets/1320525/22861992/0190839a-f126-11e6-971d-b53b1aecdc6d.png)

### System configuration

**Module versions**:
"feathers-rest": "^1.6.0",
"feathers-errors": "^2.5.0",

**NodeJS version**:
7.5.0

**Operating System**:
Windows 10 64

**Browser Version**:
FF 51.0.1

**Comment by eikaramba** [comment]
Here is my sequelize model:

```
  const user = sequelize.define('users', {
    email: {
      type: Sequelize.STRING,
      allowNull: false,
      unique: {
        args: true,
        fields: [sequelize.fn('lower', sequelize.col('email'))]
      },
      validate: {
        isUnique: function (value, next) {
          var self = this;
          user.find({where: {email: value}, attributes: ['id']})
            .then(function (user) {
              // reject if a different user wants to use the same email
              if (user && selef.id !== user.id) {
                return next('Email already taken.');
              }
              return next();
            })
            .catch(function (err) {
              return next(err);
            });
        }
      }
    },
  });
```

**Comment by daffl** [comment]
When using the Feathers client, errors get converted back into a [feathers-error](https://github.com/feathersjs/feathers-errors). Error objects are not easily `console.log`-able (but should have all the properties).. Try calling `error.toJSON()` to get it as an object.

**Comment by eikaramba** [comment]
you are right! Oh man, although i was sooo sure that i was actually not able to get the object attributes.

**Comment by daffl** [comment]
It's a little weird, which is why we had to do the https://github.com/feathersjs/feathers-errors/blob/master/src/index.js#L60 hack but we figured they should be normal JavaScript errors on the client as well which is why they are converted back.
