### ISSUE TITLE
Logging only unhandled errors

### ISSUE THREAD

**Issue by broberson** [feathersjs/feathers-errors#8]
I'm getting errors in my log for things like authentication failures and authorization failures - things that aren't really application errors at all; they're expected, a normal part of a running web app. I'd really prefer not having stack traces and everything in my logs for those kinds of things.

Is there a way I could log just the errors I'm interested in? Anything that ends up with a 500 status, perhaps?

I'd fork this and play with it, but it's been merged into feathers now, and that makes it difficult to modify without forking feathers itself just to change the dependency.

**Comment by ekryski** [comment]
Hmm. Ya that seems reasonable and has been on my radar for a while. I'm thinking at least supporting different log levels, maybe with some sane defaults.

**Comment by ekryski** [comment]
Rather than make assumptions about what people want to log, we're going to let you determine that. Therefore, we'll be moving any of this functionality to the app generator as describe here: https://github.com/feathersjs/feathers-errors/issues/11.
