### ISSUE TITLE
Getting 500 status code when attempting to throw non 500 style errors (401)

### ISSUE THREAD

**Issue by camstuart** [feathersjs/feathers-errors#85]
I was hoping to be able to control the HTTP status code by using `feathers-errors`

I have a middle-ware that places the `Authorization` header into the request object:

```JavaScript
req.feathers.authorizationHeader = req.headers.authorization || ''
```

And then, Inside my service class method I throw a Forbidden (401) if this value is not present:

```JavaScript
const errors = require('feathers-errors') // v2.9.1
const _ = require('underscore')

class Service {
  constructor(options) {
    this.options = options || {}
  }

  async find(params) {

    if (_.isEmpty(params.authorizationHeader)) {
      throw new errors.Forbidden('Access denied') // Was expecting a 401 response code but got 500
    }

  }
}

module.exports = function (options) {
  return new Service(options)
}

module.exports.Service = Service

```

The output looks like this:

```HTML
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Error</title>
    </head>
    <body>
        <pre>Forbidden: Access denied
            <br> &nbsp; &nbsp;at Forbidden (/srv/data/metinsight-apps/micro-service-authentication/node_modules/feathers-errors/lib/index.js:114:17)
            <br> &nbsp; &nbsp;at Object.find (/srv/data/metinsight-apps/micro-service-authentication/src/services/authenticate/authenticate.class.js:40:13)
            <br> &nbsp; &nbsp;at &lt;anonymous&gt;
        </pre>
    </body>
</html>
```

But the status code is 500, not 401. And I would much prefer a json object in response, not HTML

**Comment by daffl** [comment]
Are you using the [error handler middleware](https://docs.feathersjs.com/api/errors.html#rest-express-errors) and in the right place?

It will definitely set the status code accordingly if the error has one [here](https://github.com/feathersjs/feathers-errors/blob/master/src/error-handler.js#L72).

**Comment by camstuart** [comment]
Ahh yes indeed. the:

```JavaScript
app.use(notFound())
app.use(handler())
```

Where too high up in `./src/app.js` not even sure why/how that was the case.
Thankyou for your help
